* standard/SchemeCompilation.java (checkDefaultBinding): Catch 	NoClassDefFoundError so we can emit informative warning. 	* lang/Translator.java (rewrite): Change API so we can distinguidh 	when called from scan looking for macros - in which case we don't 	want to call checkDefaultBinding, both for performance, and to 	avoid a duplicate warning.